config/routes.rb
CivilSites::Application.routes.draw do
 
  get "password_resets/new"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'civilizations#index'

  resources :users
  resources :sessions
  resources :password_resets

  resources :wonders

  resources :leaders

  resources :civilizations

end

app/models/civilization.rb
class Civilization < ActiveRecord::Base
  attr_accessible :name, :notes
end

app/controllers/civilizations_controller.rb
class CivilizationsController < ApplicationController
  before_filter :authorize, only: [:edit, :update]

  # GET /civilizations
  # GET /civilizations.json
  def index
    @civilizations = Civilization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @civilizations }
    end
  end

  # GET /civilizations/1
  # GET /civilizations/1.json
  def show
    @civilization = Civilization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @civilization }
    end
  end

  # GET /civilizations/new
  # GET /civilizations/new.json
  def new
    @civilization = Civilization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @civilization }
    end
  end

  # GET /civilizations/1/edit
  def edit
    @civilization = Civilization.find(params[:id])
  end

  # POST /civilizations
  # POST /civilizations.json
  def create
    @civilization = Civilization.new(params[:civilization])

    respond_to do |format|
      if @civilization.save
        format.html { redirect_to @civilization, notice: 'Civilization was successfully created.' }
        format.json { render json: @civilization, status: :created, location: @civilization }
      else
        format.html { render action: "new" }
        format.json { render json: @civilization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /civilizations/1
  # PUT /civilizations/1.json
  def update
    @civilization = Civilization.find(params[:id])

    respond_to do |format|
      if @civilization.update_attributes(params[:civilization])
        format.html { redirect_to @civilization, notice: 'Civilization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @civilization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /civilizations/1
  # DELETE /civilizations/1.json
  def destroy
    @civilization = Civilization.find(params[:id])
    @civilization.destroy

    respond_to do |format|
      format.html { redirect_to civilizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/civilizations_helper.rb
module CivilizationsHelper
end

app/views/civilizations/_form.html.erb
<%= form_for(@civilization) do |f| %>
  <% if @civilization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@civilization.errors.count, "error") %> prohibited this civilization from being saved:</h2>

      <ul>
      <% @civilization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/civilizations/edit.html.erb
<h1>Editing civilization</h1>

<%= render 'form' %>

<%= link_to 'Show', @civilization %> |
<%= link_to 'Back', civilizations_path %>

app/views/civilizations/index.html.erb
<h1>Listing civilizations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @civilizations.each do |civilization| %>
  <tr>
    <td><%= civilization.name %></td>
    <td><%= civilization.notes %></td>
    <td><%= link_to 'Show', civilization %></td>
    <td><%= link_to 'Edit', edit_civilization_path(civilization) %></td>
    <td><%= link_to 'Destroy', civilization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Civilization', new_civilization_path %>

app/views/civilizations/new.html.erb
<h1>New civilization</h1>

<%= render 'form' %>

<%= link_to 'Back', civilizations_path %>

app/views/civilizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @civilization.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @civilization.notes %>
</p>


<%= link_to 'Edit', edit_civilization_path(@civilization) %> |
<%= link_to 'Back', civilizations_path %>