config/routes.rb
CivilSites::Application.routes.draw do
 
  get "password_resets/new"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'civilizations#index'

  resources :users
  resources :sessions
  resources :password_resets

  resources :wonders

  resources :leaders

  resources :civilizations

end

app/models/leader.rb
class Leader < ActiveRecord::Base
  attr_accessible :civilization_id, :name, :notes
end

app/controllers/leaders_controller.rb
class LeadersController < ApplicationController
  # GET /leaders
  # GET /leaders.json
  def index
    @leaders = Leader.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leaders }
    end
  end

  # GET /leaders/1
  # GET /leaders/1.json
  def show
    @leader = Leader.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leader }
    end
  end

  # GET /leaders/new
  # GET /leaders/new.json
  def new
    @leader = Leader.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leader }
    end
  end

  # GET /leaders/1/edit
  def edit
    @leader = Leader.find(params[:id])
  end

  # POST /leaders
  # POST /leaders.json
  def create
    @leader = Leader.new(params[:leader])

    respond_to do |format|
      if @leader.save
        format.html { redirect_to @leader, notice: 'Leader was successfully created.' }
        format.json { render json: @leader, status: :created, location: @leader }
      else
        format.html { render action: "new" }
        format.json { render json: @leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leaders/1
  # PUT /leaders/1.json
  def update
    @leader = Leader.find(params[:id])

    respond_to do |format|
      if @leader.update_attributes(params[:leader])
        format.html { redirect_to @leader, notice: 'Leader was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaders/1
  # DELETE /leaders/1.json
  def destroy
    @leader = Leader.find(params[:id])
    @leader.destroy

    respond_to do |format|
      format.html { redirect_to leaders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/leaders_helper.rb
module LeadersHelper
end

app/views/leaders/_form.html.erb
<%= form_for(@leader) do |f| %>
  <% if @leader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leader.errors.count, "error") %> prohibited this leader from being saved:</h2>

      <ul>
      <% @leader.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :civilization_id %><br />
    <%= f.number_field :civilization_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leaders/edit.html.erb
<h1>Editing leader</h1>

<%= render 'form' %>

<%= link_to 'Show', @leader %> |
<%= link_to 'Back', leaders_path %>

app/views/leaders/index.html.erb
<h1>Listing leaders</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Notes</th>
    <th>Civilization</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leaders.each do |leader| %>
  <tr>
    <td><%= leader.name %></td>
    <td><%= leader.notes %></td>
    <td><%= leader.civilization_id %></td>
    <td><%= link_to 'Show', leader %></td>
    <td><%= link_to 'Edit', edit_leader_path(leader) %></td>
    <td><%= link_to 'Destroy', leader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Leader', new_leader_path %>

app/views/leaders/new.html.erb
<h1>New leader</h1>

<%= render 'form' %>

<%= link_to 'Back', leaders_path %>

app/views/leaders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @leader.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @leader.notes %>
</p>

<p>
  <b>Civilization:</b>
  <%= @leader.civilization_id %>
</p>


<%= link_to 'Edit', edit_leader_path(@leader) %> |
<%= link_to 'Back', leaders_path %>