config/routes.rb
CivilSites::Application.routes.draw do
 
  get "password_resets/new"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'civilizations#index'

  resources :users
  resources :sessions
  resources :password_resets

  resources :wonders

  resources :leaders

  resources :civilizations

end

app/models/wonder.rb
class Wonder < ActiveRecord::Base
  attr_accessible :name, :notes
end

app/controllers/wonders_controller.rb
class WondersController < ApplicationController
  # GET /wonders
  # GET /wonders.json
  def index
    @wonders = Wonder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wonders }
    end
  end

  # GET /wonders/1
  # GET /wonders/1.json
  def show
    @wonder = Wonder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wonder }
    end
  end

  # GET /wonders/new
  # GET /wonders/new.json
  def new
    @wonder = Wonder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wonder }
    end
  end

  # GET /wonders/1/edit
  def edit
    @wonder = Wonder.find(params[:id])
  end

  # POST /wonders
  # POST /wonders.json
  def create
    @wonder = Wonder.new(params[:wonder])

    respond_to do |format|
      if @wonder.save
        format.html { redirect_to @wonder, notice: 'Wonder was successfully created.' }
        format.json { render json: @wonder, status: :created, location: @wonder }
      else
        format.html { render action: "new" }
        format.json { render json: @wonder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wonders/1
  # PUT /wonders/1.json
  def update
    @wonder = Wonder.find(params[:id])

    respond_to do |format|
      if @wonder.update_attributes(params[:wonder])
        format.html { redirect_to @wonder, notice: 'Wonder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wonder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wonders/1
  # DELETE /wonders/1.json
  def destroy
    @wonder = Wonder.find(params[:id])
    @wonder.destroy

    respond_to do |format|
      format.html { redirect_to wonders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/wonders_helper.rb
module WondersHelper
end

app/views/wonders/_form.html.erb
<%= form_for(@wonder) do |f| %>
  <% if @wonder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wonder.errors.count, "error") %> prohibited this wonder from being saved:</h2>

      <ul>
      <% @wonder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wonders/edit.html.erb
<h1>Editing wonder</h1>

<%= render 'form' %>

<%= link_to 'Show', @wonder %> |
<%= link_to 'Back', wonders_path %>

app/views/wonders/index.html.erb
<h1>Listing wonders</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wonders.each do |wonder| %>
  <tr>
    <td><%= wonder.name %></td>
    <td><%= wonder.notes %></td>
    <td><%= link_to 'Show', wonder %></td>
    <td><%= link_to 'Edit', edit_wonder_path(wonder) %></td>
    <td><%= link_to 'Destroy', wonder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wonder', new_wonder_path %>

app/views/wonders/new.html.erb
<h1>New wonder</h1>

<%= render 'form' %>

<%= link_to 'Back', wonders_path %>

app/views/wonders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @wonder.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @wonder.notes %>
</p>


<%= link_to 'Edit', edit_wonder_path(@wonder) %> |
<%= link_to 'Back', wonders_path %>